# Generated by Django 4.2.27 on 2025-12-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='state', max_length=70),
            preserve_default=False,
        ),
    ]
