# Generated by Django 4.2.27 on 2025-12-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.CharField(default='comment', max_length=70),
        ),
    ]
